version: '3.8'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - pocketbase
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=http://pocketbase:8090
      - NEXT_PUBLIC_AI_API_URL=http://host.docker.internal:8100
      - NODE_ENV=production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: "1001:1001"
    #restart: unless-stopped

  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - ./pb_data:/pb_data
      - ./pb_migrations:/pb_migrations
    extra_hosts:
      - "host.docker.internal:host-gateway"
            
volumes:
  pb_migrations:
  pb_data: 